### PR TITLE
Display targeted error messages for invalid inputs during the user register process

### PR DESCRIPTION
**Pull request by kartik-212004**

### CODE REVIEW

**Comment by kartik-212004** [comment]
can u label it with hacktober-fest . Please

**Comment by Ankit-Roy-CSE** [comment]
Thanks for contributing . Could you also add the targeted error messages for the username and email fields besides the password field which you already did?

**Comment by kartik-212004** [comment]
Yeah sure

**Comment by Ankit-Roy-CSE** [comment]
#30 Here's the issue

**Comment by kartik-212004** [comment]
U can assign it to me

**Pull request merged**
