### PR TITLE
Improving the user experience more better and enhancing features

### PR DESCRIPTION
**Pull request by RishiAnand108**
Key Changes:
ClassName for Font: Added className={inter.className} to the <body> tag to apply the Inter font. Consistent Formatting: Ensured consistent formatting and indentation. Context Providers: Wrapped ToasterContext inside AuthContext for better context management.

### CODE REVIEW

**Comment by RishiAnand108** [comment]
Please accept and merge my pr under the hacktober label .

**Comment by Ankit-Roy-CSE** [comment]
Your code breaks . I would suggest not changing how the children components of <AuthContext> were set up originally . Please open a PR after you fix this .

**Comment by RishiAnand108** [comment]
Please tell what improvement you want

**Comment by Ankit-Roy-CSE** [comment]
Dont wrap the ToasterContext inside AuthContext as it is causing problem in rendering the page . Let the Auth Context stay like how it was for your fix to work .

**Comment by RishiAnand108** [comment]
sir i wanna make make changes please allow me

**Comment by RishiAnand108** [comment]
i wanna make changes please allow me and merge my pr

**Pull request closed without merging**
